{
 "title": "PokéDelivery Monitoring",
 "tags": [
  "pokedelivery",
  "devops",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PokéDelivery API Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "PokéDelivery API Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds" }
   ]
  },
  {
   "title": "PokéDelivery HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code" }
   ]
  },
  {
   "title": "Jenkins Online Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jenkins_node_online_value)" }
   ]
  },
  {
   "title": "Jenkins Executors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_executor_count_value)"
    }
   ]
  },
  {
   "title": "Jenkins Free Executors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_executor_free_value)"
    }
   ]
  },
  {
   "title": "Jenkins Busy Executors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_executor_in_use_value)"
    }
   ]
  },
  {
   "title": "Central Container Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container=~\".+\"}"
    }
   ]
  }
 ]
}